FROM alpine:latest
RUN apk update && apk add curl
RUN echo '*/10 *  *  *  *    curl nginx/trigger_convert.php' > /etc/crontabs/root
RUN echo '0  */8  *  *  *   curl nginx/trigger_rescanFolders.php' >> /etc/crontabs/root

CMD  crond -l 2 -f
