version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: php-docker.local
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php-fpm
    restart: unless-stopped

  php-fpm:
    image: php:8.0-fpm
    container_name: php-fpm
    hostname: php.local
    ports:
      - "2200:22"
    volumes:
      - ./code:/code
    restart: unless-stopped


  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb.local
    ports:
      - "27040:27017"
    restart: unless-stopped
