FROM php:8.1-fpm
EXPOSE 22
RUN apt-get update && apt-get install -y \
    ffmpeg \
    cron\
    ssh \
    libmagickwand-dev --no-install-recommends \
    && pecl install imagick mongodb \
	&& docker-php-ext-enable imagick \
	&& docker-php-ext-enable mongodb \
COPY example-crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab && crontab /etc/cron.d/crontab





