FROM php:8.1-fpm
EXPOSE 22
RUN apt-get update && apt-get install -y \
    ffmpeg \
    ssh \
    libmagickwand-dev --no-install-recommends \
    && pecl install imagick mongodb \
	&& docker-php-ext-enable imagick \
	&& docker-php-ext-enable mongodb




