version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: php-docker.local
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    container_name: php
    hostname: php.local
    ports:
      - "2200:22"
    volumes:
      - ./code:/code
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb.local

    ports:
      - "27040:27017"
    restart: unless-stopped

  typer-the-converter:
      build:
        context: .
        dockerfile: Dockerfile-php
      container_name: tyler
      volumes:
        - ./code:/code
      restart: unless-stopped