version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: php-docker.local
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    hostname: php.local
    ports:
      - "2200:22"
    volumes:
      - ./code:/code
    links:
      - ffmpeg
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb.local

    ports:
      - "27017:27017"
    restart: unless-stopped

  ffmpeg:
    image: linuxserver/ffmpeg
    container_name: ffmpeg

  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    container_name: cron
    links:
      - php
    volumes:
      - ./code:/code
    restart: unless-stopped
